Version 11.3.2

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -352,7 +352,7 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 AUTOMAKE_OPTIONS = foreign
-SUBDIRS = man doc po src  
+SUBDIRS = man doc po src/madplay src
 ACLOCAL_AMFLAGS = -I m4
 EXTRA_DIST = config.rpath m4/Makefile.in src/gettext.h doc/COMPILE \
              doc/Changelog doc/License doc/Readme doc/daisy-player.* \
@@ -868,7 +868,8 @@ uninstall-am:
 
 check-gettext:
 	@if test x$(USE_NLS) != "xyes" ; then \
-	  echo "Missing gettext. Rerun configure and check for" \"'checking whether to use NLS... yes'!" ; exit 1; fi
+	  echo "Missing gettext. Rerun configure and check for" \
+	  "'checking whether to use NLS... yes'!" ; exit 1; fi
 
 update-po: check-gettext
 	@find $(srcdir)/src/ -name "*.cpp" -print | sort > $(srcdir)/po/POTFILES.in.2 ; \
