Version 11.3

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,6 +1,6 @@
 AUTOMAKE_OPTIONS = foreign
 
-SUBDIRS = man doc po src/madplay src
+SUBDIRS = man doc po src  
 
 ACLOCAL_AMFLAGS = -I m4
 
@@ -44,8 +44,7 @@ EXTRA_DIST = config.rpath m4/Makefile.in src/gettext.h doc/COMPILE \
 
 check-gettext:
 	@if test x$(USE_NLS) != "xyes" ; then \
-	  echo "Missing gettext. Rerun configure and check for" \
-	  "'checking whether to use NLS... yes'!" ; exit 1; fi
+	  echo "Missing gettext. Rerun configure and check for" \"'checking whether to use NLS... yes'!" ; exit 1; fi
 
 update-po: check-gettext
 	@find $(srcdir)/src/ -name "*.cpp" -print | sort > $(srcdir)/po/POTFILES.in.2 ; \
diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -89,13 +89,7 @@ build_triplet = @build@
 host_triplet = @host@
 subdir = .
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
-am__aclocal_m4_deps = $(top_srcdir)/m4/gettext.m4 \
-	$(top_srcdir)/m4/iconv.m4 $(top_srcdir)/m4/intlmacosx.m4 \
-	$(top_srcdir)/m4/lib-ld.m4 $(top_srcdir)/m4/lib-link.m4 \
-	$(top_srcdir)/m4/lib-prefix.m4 $(top_srcdir)/m4/nls.m4 \
-	$(top_srcdir)/m4/onceonly.m4 $(top_srcdir)/m4/po.m4 \
-	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/m4/stdbool.m4 \
-	$(top_srcdir)/configure.ac
+am__aclocal_m4_deps = $(top_srcdir)/configure.ac
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
 DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
@@ -352,7 +346,7 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 AUTOMAKE_OPTIONS = foreign
-SUBDIRS = man doc po src/madplay src
+SUBDIRS = man doc po src  
 ACLOCAL_AMFLAGS = -I m4
 EXTRA_DIST = config.rpath m4/Makefile.in src/gettext.h doc/COMPILE \
              doc/Changelog doc/License doc/Readme doc/daisy-player.* \
@@ -868,8 +862,7 @@ uninstall-am:
 
 check-gettext:
 	@if test x$(USE_NLS) != "xyes" ; then \
-	  echo "Missing gettext. Rerun configure and check for" \
-	  "'checking whether to use NLS... yes'!" ; exit 1; fi
+	  echo "Missing gettext. Rerun configure and check for" \"'checking whether to use NLS... yes'!" ; exit 1; fi
 
 update-po: check-gettext
 	@find $(srcdir)/src/ -name "*.cpp" -print | sort > $(srcdir)/po/POTFILES.in.2 ; \
